#!/usr/bin/env bash
set -euo pipefail

# Debug USDZ to GLB Conversion
# Usage: bash scripts/debug-usdz-conversion.sh

echo "=== USDZ to GLB Conversion Debugging ==="
echo ""
echo "This script helps you debug the USDZ to GLB conversion process."
echo ""

# Check if Next.js is running
if ! docker ps | grep -q "microcement-app-dev"; then
  echo "⚠️  Next.js app is not running. Start it first with:"
  echo "   bash scripts/dev-start.sh"
  echo ""
fi

echo "=== Current Status ==="
docker ps | grep -E "microcement-app-dev|usdz" || echo "No relevant containers running"
echo ""

echo "=== Where to Monitor Logs ==="
echo ""
echo "1. Next.js Server Logs (where conversion happens):"
echo "   docker logs microcement-app-dev-1 --follow"
echo ""
echo "2. Background Convert API (receives conversion requests):"
echo "   docker logs microcement-app-dev-1 --follow | grep -E 'convert|USDZ|GLB|FALLBACK'"
echo ""
echo "=== Testing the Conversion ==="
echo ""
echo "To test the conversion:"
echo "1. Upload a USDZ file from the iOS Room Scanner app"
echo "2. Watch the logs above for conversion messages"
echo "3. Look for:"
echo "   - File size information"
echo "   - [FALLBACK] messages showing conversion attempts"
echo "   - GLB file size (should be ~24-28KB for 30KB USDZ input)"
echo "   - Wall and vertex counts"
echo ""
echo "=== Expected Output ==="
echo ""
echo "Good conversion (24-28KB GLB from 30KB USDZ):"
echo "  - Should see wall extraction (4+ walls)"
echo "  - Should see hundreds of vertices"
echo "  - GLB size should be close to USDZ size"
echo ""
echo "Bad conversion (2-4KB GLB, shows red square):"
echo "  - Only fallback geometry (8 vertices)"
echo "  - Very small GLB file"
echo "  - Likely USDZ parsing failed"
echo ""
echo "=== Debug Commands ==="
echo ""
echo "Watch logs in real-time:"
echo "  docker logs microcement-app-dev-1 --follow 2>&1 | grep -E 'convert|USDZ|GLB|FALLBACK|Wall|vertex'"
echo ""
echo "Check recent conversion attempts:"
echo "  docker logs microcement-app-dev-1 2>&1 | tail -100 | grep -E 'convert|USDZ|GLB|FALLBACK'"
echo ""
echo "Check GLB files created:"
echo "  ls -lh public/models/scanned-rooms/*/*.glb 2>/dev/null || echo 'No GLB files found'"
echo ""
echo "=== Restart Services ==="
echo ""
echo "If you need to restart after making changes:"
echo "  docker restart microcement-app-dev-1"
echo "  # OR"
echo "  bash scripts/dev-start.sh"
echo ""
